### ISSUE TITLE
Permission error - WRFChem python 3.8

### ISSUE THREAD

**Issue by EECJC17** [wrfchem-leeds/WRFotron#26]
What happened: When running WRFChem 4.2, no output was generated. I checked pre.bash.e* and it showed the following error:

PermissionError: [Errno 13] Permission denied: '/nobackup/WRFChem/anaconda3/lib/python3.8/site-packages/xesmf-0.5.1.dist-info'

I am wondering if this is because I'm a new user?

I am using the default cemac WRFotron

**Comment by lukeconibear** [comment]
Currently, there is an issue with the CEMAC WRFChem module on ARC4. This will stop `main.bash` from creating `wrfout` files. We are working to fix this and I will update you here when it is solved.

On a separate note, this shouldn't affected `pre.bash`. In general, the first error that occurs in a WRFChem run often then trips up the rest of the run. So it is best practise to check each step of the preprocessing in turn to ensure that all were correct. This can be done by looking at the (bottoms of the) log files for each step: `ungrib`, `geogrid`, `metgrid`, `first_real_out`, `anthro_emis`, `fire_emis`, `second_real_out`, `mozbc`.

To speed up this step checking, you could add this alias to your `~/.bashrc` file, and then you can just type `wrfpreedgar` to see whether all 8 steps were successful.

```bash
alias wrfpreedgar='tail -n 1 ungrib.log | grep -i success ; tail -n 1 geogrid.log | grep -i success ; tail -n 1 metgrid.log | grep -i success ; tail -n 1 first_real_out/rsl.error.0000 | grep -i success ; tail -n 2 anthro_emis.out | head -1 | grep -i success ; tail -n 2 fire_emis.out | head -1 | grep -i success ; tail -n 1 second_real_out/rsl.error.0000 | grep -i success ; tail -n 1 mozbc_bc.log | grep -i success'
```

Also, the XESMF is a python package for regridding, which is only used in optional postprocessing (`pp_concat_regrid.py`). So this shouldn't be an issue here.

**Comment by EECJC17** [comment]
Thanks for the help! that shortcut looks really useful.

**Comment by chmltf** [comment]
Something similar is happening for me (also WRFv4.2), also in the pre.bash. The run aborts very early. Gets through geogrid, metgrib and ungrib successfully and that is it.  I manually compile WRF-Chem and in my config.bash load these modules:

```
Currently Loaded Modulefiles:
  1) licenses              3) intel/19.0.4          5) intelmpi/2019.4.243   7) ncl/6.5.0             9) wrfchemconda/3.7
  2) sge                   4) user                  6) netcdf/4.6.3          8) nco/4.6.0
```

This is what my pre.bash.exxxx looks like.

```
Name of source model =>ECMWF
 Name of source model =>ECMWF
 Name of source model =>ECMWF
 Name of source model =>ECMWF
 Name of source model =>ECMWF
 Name of source model =>ECMWF
 Name of source model =>ECMWF
 Name of source model =>ECMWF
 Name of source model =>ECMWF
 Name of source model =>ECMWF
 Name of source model =>ECMWF
 Name of source model =>ECMWF
 Name of source model =>ECMWF
 starting wrf task            0  of            1
[d10s10b1:108880] *** An error occurred in MPI_Comm_create_keyval
[d10s10b1:108880] *** reported by process [140735916933121,140733193388032]
[d10s10b1:108880] *** on communicator MPI_COMM_WORLD
[d10s10b1:108880] *** MPI_ERR_ARG: invalid argument of some other kind
[d10s10b1:108880] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[d10s10b1:108880] ***    and potentially your MPI job)
netcdf error
mv: cannot stat ‘wrfbiochemi_d01’: No such file or directory
ncatted: ERROR file /nobackup/chmltf/AIRPROw_202/run/wrfbiochemi_d01_AIRPROw_202 neither exists locally nor matches remote filename patterns
ncks: ERROR file wrfinput_d01 neither exists locally nor matches remote filename patterns
File err
ln: failed to create symbolic link ‘./anthro_emis.inp’: File exists
Traceback (most recent call last):
  File "sum_sector_emiss_wrfchemi.py", line 2, in <module>
    import xarray as xr
  File "/nobackup/cemac/software/apps/wrfchemconda/3.7/1/default/lib/python3.8/site-packages/xarray/__init__.py", line 1, in <module>
    import pkg_resources
  File "/nobackup/cemac/software/apps/wrfchemconda/3.7/1/default/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3261, in <module>
    def _initialize_master_working_set():
  File "/nobackup/cemac/software/apps/wrfchemconda/3.7/1/default/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3244, in _call_aside
    f(*args, **kwargs)
  File "/nobackup/cemac/software/apps/wrfchemconda/3.7/1/default/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3273, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/nobackup/cemac/software/apps/wrfchemconda/3.7/1/default/lib/python3.8/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws = cls()
  File "/nobackup/cemac/software/apps/wrfchemconda/3.7/1/default/lib/python3.8/site-packages/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/nobackup/cemac/software/apps/wrfchemconda/3.7/1/default/lib/python3.8/site-packages/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/nobackup/cemac/software/apps/wrfchemconda/3.7/1/default/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2075, in find_on_path
    for dist in factory(fullpath):
  File "/nobackup/cemac/software/apps/wrfchemconda/3.7/1/default/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2140, in distributions_from_metadata
    if len(os.listdir(path)) == 0:
PermissionError: [Errno 13] Permission denied: '/nobackup/WRFChem/anaconda3/lib/python3.8/site-packages/xesmf-0.5.1.dist-info'
netcdf error
 starting wrf task            0  of            1
[d10s10b1:108992] *** An error occurred in MPI_Comm_create_keyval
[d10s10b1:108992] *** reported by process [140731629240321,140728898420736]
[d10s10b1:108992] *** on communicator MPI_COMM_WORLD
[d10s10b1:108992] *** MPI_ERR_ARG: invalid argument of some other kind
[d10s10b1:108992] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[d10s10b1:108992] ***    and potentially your MPI job)
 in module_wrfchem_lib ...
cp: cannot stat ‘/nobackup/chmltf/AIRPROw_202/restart/base/wrfrst_d01_2016-11-14_00:00:00’: No such file or directory
cp: cannot stat ‘/home/home02/chmltf/WRFotrons/WRFotron_WRF4.0/pp_concat_regrid.py’: No such file or directory
cp: cannot stat ‘/home/home02/chmltf/WRFotrons/WRFotron_WRF4.0/pp_concat_regrid.bash’: No such file or directory
```
I am able to run WRFv3.7.1 no problem with the same module list.

**Comment by lukeconibear** [comment]
Sorry both, there are different issues here.

A few Python packages for the `wrfchemconda/3.7` module were updated recently, which changed the access permissions. These permission errors should now be resolved.

This should fix the issue for Lauren as you manually compile WRFChem. Let me know if it doesn't.

For Connor, as you use the CEMAC compilation of WRFChem4.2, there is still this remaining issue for `wrf.exe`. We are working to resolve this ASAP and I will update you when it is fixed.

**Comment by chmltf** [comment]
Thanks, the permission error is gone now. I still have this in my pre.bash.exxxx that terminates the job early.

```
[d10s10b1:108880] *** An error occurred in MPI_Comm_create_keyval
[d10s10b1:108880] *** reported by process [140735916933121,140733193388032]
[d10s10b1:108880] *** on communicator MPI_COMM_WORLD
[d10s10b1:108880] *** MPI_ERR_ARG: invalid argument of some other kind
[d10s10b1:108880] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[d10s10b1:108880] ***    and potentially your MPI job)
netcdf error
```
Here is the run directory if you'd like to have a look.
/nobackup/chmltf/AIRPROw_202/run/base/2016-11-13_00:00:00-2016-11-16_00:00:00

**Comment by lukeconibear** [comment]
Okay, thanks for the update.

I cannot see into that path, could you make make it readable please? (`chmod a+rx -R AIRPROw_202`)

**Comment by chmltf** [comment]
sorry, thought I did this! Hopefully you can see it now.

**Comment by lukeconibear** [comment]
That's okay, that works, thanks.

This netcdf error which first occurs for `first_real_out` may be a consequence of the spawned processes running on the ARC4 cores not locating the correct netcdf module. This may be separate to the loaded modules on the login nodes.

This is an issue I have recently noticed in a separate context for other tests. The solution was to add `netcdf/4.6.3` to the loaded modules at the top of `config.bash`. So in your case, considering your manual compilation, replace:
```bash
module load ncl/6.5.0 nco/4.6.0 wrfchemconda/3.7
```
With:
```bash
module load netcdf/4.6.3 ncl/6.5.0 nco/4.6.0 wrfchemconda/3.7
```
Let me know if this works.

**Comment by chmltf** [comment]
Thanks for taking a look. I ran again with this addition and am unfortunately getting the same errors in the pre.bash.exxxxx.

**Comment by lukeconibear** [comment]
Okay.

Well, the error message mentions issues with MPI communications. So maybe next it's worth trying also loading the modules that were used in the MPI compilation i.e. `intel/19.0.4` and `openmpi/3.1.4` (into the same place in `config.bash`)?

Has this manually compilation successfully run before (especially `real.exe` from `/nobackup/chmltf/WRFChem/WRFMeteo4.2`)?

**Comment by chmltf** [comment]
I've tried adding openmpi (instead of intelmpi) and still get an MPI error, although this time MPI COMM error/netcdf error. 

It is my first time running after recompiling so I will try compiling again and see if that fixes it.

**Comment by lukeconibear** [comment]
Okay, it does sound like a compiler issue.

A while ago I updated the user guide for the manual compilation setup [here](https://wrfotron.readthedocs.io/en/latest/compilation.html#compile-wps-wrfmeteo-and-wrfchem), which you should be able to copy and paste.

If this doesn't work, let me know the path to the compilation and I can have a look.

**Comment by chmltf** [comment]
**Solution**
1. For the error saying: `An error occurred in MPI_Comm_create_keyval`. The problem was that I compiled WRFChem/WPS/WRFMeteo with openmpi and was submitting runs with intelmpi loaded. An easy fix would be to submit a run with openmpi loaded instead. However, my preprocessors were compiled with intelmpi and therefore I only have the linked libraries if intelmpi is loaded. I could not figure out how to compile the preprocessors with openmpi. intelmpi and openmpi are not compatible and cannot both be loaded. The solution for me was to recompile WRFChem/WPS/WRFMeteo with intelmpi.
2. `netcdf error` has a separate fix. This was due to namelist.wrf settings. The metgrid.log pointed me to this.  I needed to change the `num_metgrid_soil_levels` and `num_land_cat`. I am not sure why these changed, but I must have changed them while changing chemical mechanisms at some point.

Sorry I have hijacked this thread. I had the permission error, but it turns out I had others, too!

**Comment by lukeconibear** [comment]
Thanks for the solution summary here Lauren, I appreciate it.

It sounds like you have this solved now.

Though for part 1, was there a specific preprocessor that wouldn't compile for you or an error message? They all compile okay for me with: `intel/19.0.4`, `openmpi/3.1.4`, and `netcdf/4.6.3`.

**Comment by chmltf** [comment]
I got an error message when compiling the preprocessors with intel/19.0.4, openmpi/3.1.4, and netcdf/4.6.3.  I don't remember exactly what it said to put it here. I'd try again now but I've got a run going. I will in the future though and let you know if I'm struggling with it.

It's solved! Thanks for the advice.

**Comment by lukeconibear** [comment]
Great. Yes, I agree, it's best to leave it alone now that everything works.
I'll close this issue.

**Comment by lukeconibear** [comment]
Just to confirm, the CEMAC WRFChem modules for 4.2 and 3.7.1 are fully working again.
